### ISSUE TITLE
Default Keymap with ctrl-r slows down symbols-view:toggle-file-symbols

### ISSUE THREAD

**Issue by Gee-Bee** [hmatsuda/rails-transporter#66]
`ctrl-r` is by default taken by `symbols-view:toggle-file-symbols`.
After installing this extension going to symbol dialog is slowed down (waiting for keystrokes from this extension for a second).

My suggestion is to change `ctrl-r` to `ctrl-t`.
`ctr-t` is taken by `fuzzy-finder:toggle-file-finder`, but this is also mapped to `ctrl-p` which most people use (imho).

As a quick workaround for this issue put this in your ~/.atom/keymap.cson
```cson
'.platform-linux':
  'ctrl-t': 'unset!'
'atom-workspace':
  'ctrl-r c':   'unset!'
  'ctrl-r v f': 'unset!'
  'ctrl-r v':   'unset!'
  'ctrl-r l':   'unset!'
  'ctrl-r m':   'unset!'
  'ctrl-r h':   'unset!'
  'ctrl-r s':   'unset!'
  'ctrl-r p':   'unset!'
  'ctrl-r a':   'unset!'
  'ctrl-r d m': 'unset!'
  'ctrl-r f':   'unset!'
  'ctrl-t c':   'rails-transporter:open-controller'
  'ctrl-t v f': 'rails-transporter:open-view-finder'
  'ctrl-t v':   'rails-transporter:open-view'
  'ctrl-t l':   'rails-transporter:open-layout'
  'ctrl-t m':   'rails-transporter:open-model'
  'ctrl-t h':   'rails-transporter:open-helper'
  'ctrl-t s':   'rails-transporter:open-spec'
  'ctrl-t p':   'rails-transporter:open-partial-template'
  'ctrl-t a':   'rails-transporter:open-asset'
  'ctrl-t d m': 'rails-transporter:open-migration-finder'
  'ctrl-t f':   'rails-transporter:open-factory'
```

**Comment by hmatsuda** [comment]
@Gee-Bee Thanks for reporting. I have to change keymap on platform-linux but why you think most people mapped to `ctrl-p`?
I think it's not good to use core package's keymaps.

**Comment by Gee-Bee** [comment]
What I meant is:
- `ctrl-r` is mapped to `symbols-views:toggle-file-symbols` by default
- `ctrl-t` and `ctrl-p` are both mapped to `fuzzy-finder:toggle-file-finder` by default
- I use `ctrl-r` to go to a symbol a lot and I don't want it to be slowed down
- For `fuzzy-finder:toggle-file-finder` I use `ctrl-p` (probably because of its resemblence to `ctrl-shift-p` mapped to `command-palette:toggle`), which makes `ctrl-t` perfect candidate for *rails-**t**ransporter*

Big thank you for creating this plugin. My work as a rails developer is much more effective now in Atom.

**Comment by hmatsuda** [comment]
Understand. I can't override `ctrl-t` because I think probably some people use `ctrl-t` as `fuzzy-finder:toggle-file-finder` on linux platform. if you have other alternatives, please let me know.

Thanks.

**Comment by art-solopov** [comment]
`Alt-r` maybe?

**Comment by hmatsuda** [comment]
@art-solopov  Thanks for suggestion. I tried to configure `Alt-r` on my ubuntu but it doesn't work well I think it's keymap focuses application's menu bar.
