### ISSUE TITLE
Triggering open view on controller should check for render methods

### ISSUE THREAD

**Issue by joseramonc** [hmatsuda/rails-transporter#70]
For example, when triggering the open command on a scaffolded controller, if you call the method inside a `def create` or a `def update` method, it ask you to create a new file for that method, but those methods usually render other view, (new and edit respectively), is it possible to prompt to open rendered method or to create the new file? something like this prompt.
![screen shot 2015-05-12 at 10 05 17 pm](https://cloud.githubusercontent.com/assets/1993929/7603102/032a08a2-f8f3-11e4-8381-63b3454c256b.png)

I don't know if I'm clear enough

**Comment by hmatsuda** [comment]
@joseramonc It's nice feature but I have no idea in the below situation which view should we open?
```
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
```

**Comment by joseramonc** [comment]
I was thinking that initially, only search for all `render`s, (`render 'view'` and `render :view`) once there, maybe start searching for all `redirect_to` and more complex things like multiple formats.

In your example, to prompt for `create`(html), `new`(html) and  `show`(html) seems enough for me.

**Comment by hmatsuda** [comment]
@joseramonc  OK I guess it's possible. I won't work on this because usually I use `open-view-finder` in this situation but I'm not opposed to add this feature. If you implement this, I would merge it in.
