### ISSUE TITLE
rails-transporter:open-model ignores non-namespaced models

### ISSUE THREAD

**Issue by mysmallidea** [hmatsuda/rails-transporter#75]
`rails-transporter:open-model` looks for models under the same namespace as the view or controller. It does not find models that are not in the same namespace as the controller or view. 

For example, I have a controller app/controllers/admin/members_controller.rb. My model is in app/models/member.rb. Launching `rails-transporter:open-model` does not find the model, but instead brings up a dialog like the following: 

![non-namespaced_model](https://cloud.githubusercontent.com/assets/234/9484762/32ddf858-4b76-11e5-97bb-bf6f122b6492.png)

**Comment by hmatsuda** [comment]
@mysmallidea Sorry for the delay in fixing, latest version of this pacekage's `open-model` now supports to open non-namespaced models from controller.

Thanks.

**Comment by JustinAiken** [comment]
Thanks!  This just got 10x more useful in my heavily namespaced project!

**Comment by mysmallidea** [comment]
:satisfied:
