### ISSUE TITLE
Open "default" related file with common command

### ISSUE THREAD

**Issue by Soleone** [hmatsuda/rails-transporter#76]
### Problem

Right now you need to know a lot of shortcuts to open related files. It would be great if the user experience could be made a bit easier.

For example my main uses cases right now (90% of the time) are switching between a controller and its tests or a model and its test. So you're focussing on two files and want to switch between them quickly. Right now I have to press know 3 keyboard shortcuts for this work flow. 

### Suggestion

Optimally you could use the same keyboard shortcut to switch between the test and implementation back and forth.

There could be a new quick command e.g. `'ctrl-alt-r': 'rails-transporter:toggle-test` that detects your current context and brings you to the most likely file you want to go (imho it should switch between test and implementation, but maybe that's not true for everyone, not sure if it should be configurable).

```coffeescript
toggleTest: ->
  if @isTest(@currentFile)
    # not trivial right now to call either @openModel(), @openController() or @openHelper()
  else
    @openTest()
```

**Comment by bronson** [comment]
Check out the ruby-test-switcher plugin, sounds like it does just what you want.

I don't like the way it overrides the `cmd-.` keystroke anyway...  Disable its keymap in its settings, then you can map your keystroke like this:

```coffee
'atom-workspace':
  'ctrl-alt-r': 'ruby-test-switcher:switch-without-split'
```

**Comment by Soleone** [comment]
Thanks! That plugin seems to do what I want, but the problem is that it takes 20 seconds (!) in my huge project to switch between two related files even if both are already open as tabs.
