### ISSUE TITLE
viewFileExtension fallback

### ISSUE THREAD

**Issue by kwent** [hmatsuda/rails-transporter#79]
Hi,

I have an action only available via ajax with a javascript file associated no `html.erb` file but a `js.haml` file and of course `rails-transporter` is trying to open `html.erb` but fail.

If `html.erb` is not found we should try `html.haml` etc...

A priority list should be configurable and a default should be like :

```
html.erb
html.haml
js.erb
js.haml
...
```

Regards

**Comment by hmatsuda** [comment]
@kwent Thanks for reportiing the issue. I added viewFileExtensionFallbacks option. Please update package.
https://github.com/hmatsuda/rails-transporter#viewfileextensionfallbacks

You can set following value so that your problem fixes.
`html.haml, js.erb, js.haml`

best regards.

**Comment by kwent** [comment]
@hmatsuda Amazing thanks !
