### ISSUE TITLE
a plural issue when `open controller` in model/broadcaster_info.rb

### ISSUE THREAD

**Issue by Pleasurazy** [hmatsuda/rails-transporter#80]
Hi, I am rails noob, this package amazing, it save my life, and make my finger faster.

When I order `open controller` in file `model/broadcaster_info.rb` it just notify me:
`No /app/controllers/broadcaster_infoes_controller.rb found`

But in rails console:

```
DEVELOPMENT [5] live-frontend(main)> 'broadcaster_info'.pluralize
"broadcaster_infos"
```

Which plural is correct?

- Rails 3.2.13
- ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin15.0]

**Comment by hmatsuda** [comment]
@Pleasurazy Thanks for report. I'll ship a version-1.3.1 with this fixes as soon as possible. 
If you have problem after update package, please reopen this issue.

Thanks.
