### ISSUE TITLE
Allow multiple View File Extensions

### ISSUE THREAD

**Issue by bronson** [hmatsuda/rails-transporter#85]
My project mostly has .html.haml views, but some are .html.erb.

Any chance you could allow multiple View File Extensions?  I would set my prefs to `html.erb, html.slim, html.haml`.  If rails-transporter opened the first view it finds then, like Rails, it would prefer .erb over all others.

This would work for all my projects.

**Comment by hmatsuda** [comment]
@bronson Yesterday I added View File Extension Fallback options.
https://github.com/hmatsuda/rails-transporter#viewfileextensionfallbacks

Can following settings work well in your use case senario?
```
View File Extension: 'html.erb'
View File Extention Fallbacks: 'html.slim, html.haml'
```

**Comment by bronson** [comment]
Works great!  Very impressive.

Curious, why not just let View File Extensions accept a comma-separated list and have a single field?

**Comment by hmatsuda** [comment]
Do you prefer single field like this?
```
View FIle Extension: 'html.erb, html.slim, html. haml'
```

**Comment by bronson** [comment]
I would.  That seems simpler to me and still backward compatible.

Also, is there any downside to making "html.erb, html.slim, html.haml" the default?

**Comment by hmatsuda** [comment]
I agree with your opinion so I decided sigle field this and it's default value is `html.erb, html.slim, html.haml`.

**Comment by bronson** [comment]
Love it!
