### ISSUE TITLE
Sort migrations in reverse order?

### ISSUE THREAD

**Issue by bronson** [hmatsuda/rails-transporter#86]
I almost always want to open the most recent migration.  Even if not, it'll probably be one of the last two or three.

Would it be easy to sort the migrations in reverse order so the most recent ones are right at the top?

**Comment by hmatsuda** [comment]
@bronson Thank you for giving the good proposal idea. I changed `open-migration-finder`'s sort to reverse order in v1.6.1.

**Comment by bronson** [comment]
Works great, huge thanks!
