### ISSUE TITLE
using text.erb file extension doesn't work?

### ISSUE THREAD

**Issue by bronson** [hmatsuda/rails-transporter#87]
Hi, any idea why Transporter can't find `app/views/error_mailer/outside_outlines.text.erb`?

I set my View File Extension to: `html.erb, text.erb, html.slim, html.haml`

Then I navigate to my mailer's action and ask Transporter to navigate to the view.  Transporter claims "no target file found" and suggests `app/views/error_mailer/outside_outlines.html.erb`.

I change the `html` to `text` and hit return.  The file opens!  Shouldn't Transporter have found it?

This gif might illustrate what I'm doing.

![bug3](https://cloud.githubusercontent.com/assets/1776/12286576/38aaaca0-b97a-11e5-9ee1-6faff0a156a0.gif)

**Comment by hmatsuda** [comment]
This issue occured when active editor is opening the mailer file, so can you update to latest version? If you have any problems, please reopen this.

Thanks!

**Comment by bronson** [comment]
works perfect.  thank you!
