### ISSUE TITLE
[Request] Check factories for singular and plural

### ISSUE THREAD

**Issue by JustinAiken** [hmatsuda/rails-transporter#88]
If editing `app/models/foo.rb`, what about if Open Factory checked for either `spec/factories/foo.rb` or `spec/factories/foos.rb` - Singluar/pluraziation of those files seems a lot less consistent across a lot of projects I've come on that models/etc..

**Comment by hmatsuda** [comment]
@JustinAiken Thanks for reporting. This package supports to open singular factory file from model or model spec version 1.6.5 or later so please upgrade to latest package.
If you have any problems, please reopen this issue.

Thanks!

**Comment by JustinAiken** [comment]
Yeaaah, no more Command-T and trying to guess the minimum number of letters in "spec factory someothing" I can get away with like a schmuck!  Thanks :)
